programowanie_w_zastosowaniach/get_your_home/urls.py
from datetime import datetime

from django.urls import path, register_converter

from . import views
from django.contrib.auth.views import LogoutView


class DateConverter:
    regex = r'\d{4}-\d{1,2}-\d{1,2}'
    format = '%Y-%m-%d'

    def to_python(self, value):
        return datetime.strptime(value, self.format).date()

    def to_url(self, value):
        return value.strftime(self.format)


register_converter(DateConverter, 'date')

urlpatterns = [
    path("", views.list_of_sale_announcement, name='index'),
    path("login/", views.login_view, name='login_form'),
    path("register/", views.register_view, name='register_form'),
    path('logout/', LogoutView.as_view(next_page=""), name='logout'),
    path("profile/", views.profile_view, name='profile_view'),
    path("add/", views.add_announcement, name='add_new_announcement'),
    path("view/<date:publication_date>/<city>/<street>/<number>/", views.details, name="details"),
    path("view/<date:publication_date>/<city>/<street>/<number>/admin", views.admin_adit_ann, name="admin_edit"),
    path("view/<date:publication_date>/<city>/<street>/<number>/edit", views.edit_announcement, name="edit_ann"),
    path("filter/", views.list_of_sale_announcement, name="filtered_list"),
    path("profile/password_change/", views.password_change, name="password_change"),
    path("profile/user_data_change/", views.change_user_data, name="user_data_change"),
]

programowanie_w_zastosowaniach/programowanie_w_zastosowaniach/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('get_your_home.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

programowanie_w_zastosowaniach/get_your_home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy

# TODO: Dodać polskie tłumaczenia
def post_code_validator(value: str):
    if len(value) != 6:
        raise ValidationError(
            gettext_lazy("%(value)s must contains exactly 6 characters"),
            params={"value": value},
        )
    if value[2] != '-':
        raise ValidationError(
            gettext_lazy("%(value)s must contains '-' at 3rd character"),
            params={"value": value},
        )
    for char in value[0:3:6]:
        try:
            int(char)
        except ValueError:
            raise ValidationError(
                gettext_lazy("Invalid character '%(char)s' in given post code - each character must be a number"),
                params={"char": char},
            )


class Photo(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Zdjęcie'
        verbose_name_plural = 'Zdjęcia'


class SaleAnnouncement(models.Model):
    HEATING_TYPES = {
        "unknown": "Nie podany",
        "gas": "Ogrzewanie gazowe",
        "electric": "Ogrzewanie elektryczne",
        "oil": "Ogrzewanie olejowe",
        "biomass": "Ogrzewanie na biomasę",
        "underfloor_water": "Ogrzewanie podłogowe wodne",
        "solar": "Ogrzewanie słoneczne",
        "heat_pump": "Pompy ciepła",
        "steam": "Ogrzewanie parowe",
        "hot_water": "Ogrzewanie wodne",
        "fireplace": "Ogrzewanie kominowe"
    }

    PROPERTY_TYPES = {
        "studio": "Mieszkanie jednopokojowe (kawalerka)",
        "m2": "Mieszkanie dwupokojowe",
        "m3": "Mieszkanie trzypokojowe",
        "m4": "Mieszkanie czteropokojowe",
        "apartment": "Apartament",
        "loft": "Loft",
        "single_family_house": "Dom jednorodzinny",
        "apartment_building": "Mieszkanie w bloku mieszkalnym",
        "tenement_house": "Mieszkanie w kamienicy",
        "townhouse": "Dom szeregowy",
        "dormitory": "Mieszkanie w akademiku (dla studentów)"
    }

    STATUSES = {
        "canceled": "Anulowane",
        "sold": "Sprzedane",
        "blocked": "Zablokowane",
        "purchase": "Do kupienia",
        "rental": "Do wynajęcia",
        "long_term_lease": "Wynajem długoterminowy",
        "short_term_lease": "Wynajem krótkoterminowy",
        "co_ownership": "Współwłasność",
        "tenancy": "Dzierżawa",
        "commercial_property": "Nieruchomość komercyjna",
    }

    type = models.CharField(
        choices=PROPERTY_TYPES,
        max_length=len(max(PROPERTY_TYPES, key=len)),
    )
    status = models.CharField(
        choices=STATUSES,
        max_length=len(max(STATUSES, key=len)),
    )
    heating_type = models.CharField(
        choices=HEATING_TYPES,
        max_length=len(max(HEATING_TYPES, key=len)),
        default="unknown",
        null=True
    )
    area = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )
    address_city = models.CharField(
        max_length=50
    )
    address_street = models.CharField(
        max_length=150
    )
    address_post_code = models.CharField(
        max_length=6,
        validators=[post_code_validator],
    )
    address_number = models.CharField(
        max_length=20
    )
    number_of_rooms = models.SmallIntegerField()
    price = models.DecimalField(
        max_digits=100000,
        decimal_places=2,
        null=False
    )
    description = models.CharField(
        max_length=5000,
        null=True
    )
    build_year = models.SmallIntegerField(
        null=True
    )

    owner_user = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,
    )

    photos = models.ManyToManyField(
        Photo
    )

    admin_note = models.CharField(
        max_length=5000,
        null=True,
    )

    publication_date = models.DateField()

    def __str__(self):
        return (
            f'{self.address_city} - {self.address_street} {self.address_number} - {self.address_post_code} / '
            f'{self.STATUSES.get(str(self.status))}'
        )

    @property
    def get_url_date(self):
        return self.publication_date.strftime("%Y-%m-%d")

    class Meta:
        verbose_name = 'Ogłoszenie'
        verbose_name_plural = 'Ogłoszenia'

programowanie_w_zastosowaniach/get_your_home/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from .models import SaleAnnouncement
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

from .utils import get_context_to_filter, check_fields, save_photo, validate_add_edit_ann_request, \
    get_required_fields_and_num_fields_for_announcement, delete_photo

_skip_statutes = ["canceled", "sold", "blocked"]


# This view is used as index
def list_of_sale_announcement(request):
    announcements = SaleAnnouncement.objects.all().exclude(
        status__in=_skip_statutes,
    )

    context = get_context_to_filter(True, _skip_statutes)

    if request.GET:
        req = request.GET
        to_sort_base = {
            "type": req.get('typeOfAnn', 'all'),
            "status": req.get('typeOfStatus', 'all'),
            "heating_type": req.get('typeOfHeating', 'all'),
            "area__gte": req.get('minArea', '-1'),
            "area__lte": req.get('maxArea', '-1'),
            "city": req.get("city", "all"),
            "street": req.get("city", "all"),
            "number_of_rooms__gte": req.get('minRoomsNumber', '-1'),
            "number_of_rooms__lte": req.get('maxRoomsNumber', '-1'),
        }
        to_sort = {
            k: v for k, v in to_sort_base.items() if v not in ['-1', 'all', '']
        }
        announcements = announcements.filter(**to_sort)

    context.update({
        "announcements": {
            announcement: announcement.photos.first() for announcement in announcements
        }
    })

    return render(
        request=request,
        template_name="index.html",
        context=context,
    )


# TODO: Save state
def login_view(request):
    template_name_to_use = 'account/login.html'
    if request.method == "POST":
        error_message = check_fields(request.POST, {
            "username": "nazwa użytkownika",
            "password": "hasło"
        })
        username = request.POST.get("username", '')
        password = request.POST.get("password", '')
        if error_message:
            return render(
                request=request,
                template_name=template_name_to_use,
                context={
                    "warning": error_message
                }
            )
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect("/")

        return render(
            request=request,
            template_name=template_name_to_use,
            context={
                "warning": "Email lub hasło, jest błędne, spróbuj ponownie"
            }
        )

    return render(
        request=request,
        template_name=template_name_to_use,
        context={}
    )


# TODO: Save state
def register_view(request):
    template_name_to_use = 'account/register.html'

    if request.method == "POST":
        error_message = check_fields(request.POST, {
            "username": "nazwa użytkownika",
            "password": "hasło",
            "email": "email"
        })
        if error_message:
            return render(
                request=request,
                template_name=template_name_to_use,
                context={
                    "warning": error_message
                }
            )

        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")

        users = User.objects.filter(username=username) | User.objects.filter(email=email)
        if users:
            return render(
                request=request,
                template_name=template_name_to_use,
                context={
                    "warning": "Konto o takiej nazwe użytkownika, lub emailem istnieje"
                }
            )

        user = User.objects.create_user(
            username=username,
            password=password,
            email=email,
        )

        user.first_name = request.POST.get("firstName", "")
        user.last_name = request.POST.get("lastName", "")
        user.save()
        login(request, user)
        return HttpResponseRedirect("/")

    return render(
        request=request,
        template_name=template_name_to_use,
        context={}
    )


@login_required(login_url="/login/")
def profile_view(request):
    announcements = SaleAnnouncement.objects.all().filter(
        owner_user__email__regex=request.user.email
    )
    return render(
        request=request,
        template_name="account/profile.html",
        context={
            "announcements": {
                announcement: announcement.photos.first() for announcement in announcements
            }
        }
    )


def details(request, publication_date, city, street, number):
    announcement = SaleAnnouncement.objects.get(
        address_city=city,
        address_street=street,
        address_number=number,
        publication_date=publication_date
    )

    if not announcement:
        raise Http404()

    photos = announcement.photos.all()

    context = {
        "ann": announcement,
        "photos": photos,
        "owner": announcement.owner_user.id == request.user.id
    }

    return render(
        request=request,
        template_name="announcement/details.html",
        context=context
    )


@login_required(login_url="/login/")
def add_announcement(request):
    base_context = get_context_to_filter(statuses_to_skip=_skip_statutes)
    template_to_use = "announcement/add_edit_announcement.html"
    if request.POST:
        # Walidacja wymaganych pól
        error_message = validate_add_edit_ann_request(
            request.POST,
            *get_required_fields_and_num_fields_for_announcement()
        )
        if error_message:
            context = {
                'warning': error_message
            } | base_context
            return render(request, template_to_use, context)

        # Tworzenie nowego ogłoszenia
        new_announcement = SaleAnnouncement(
            type=request.POST.get('typeOfAnn'),
            price=request.POST.get('price'),
            status=request.POST.get('typeOfStatus'),
            heating_type=request.POST.get('heating_type'),
            area=request.POST.get('area'),
            address_city=request.POST.get('city'),
            address_street=request.POST.get('street'),
            address_number=request.POST.get('addressNumber'),
            address_post_code=request.POST.get('postCode', ''),
            number_of_rooms=request.POST.get('roomsNumber'),
            description=request.POST.get('description', ''),
            build_year=request.POST.get('buildYear'),
            owner_user_id=request.user.id,
            publication_date=datetime.date.today(),
        )

        photo = request.FILES.get('photo', '')
        if not photo:
            context = {
                "warning": "Zdjęcie jest wymagane."
            } | get_context_to_filter()
            return render(
                request=request,
                template_name=template_to_use,
                context=context
            )

        if SaleAnnouncement.objects.exclude(
            status__in=_skip_statutes
        ).filter(
            address_city=new_announcement.address_city,
            address_street=new_announcement.address_street,
            address_number=new_announcement.address_number,
        ).first():
            context = {
                "warning": "Istnieje już aktywne ogłoszenie z takim adresem."
            } | get_context_to_filter()
            return render(
                request=request,
                template_name=template_to_use,
                context=context
            )

        new_announcement.save()
        new_photo = save_photo(new_announcement, photo)
        new_announcement.photos.add(new_photo)
        new_announcement.save()

        return redirect(
            details.__name__,
            publication_date=new_announcement.publication_date,
            city=new_announcement.address_city,
            street=new_announcement.address_street,
            number=new_announcement.address_number
        )

    return render(
        request=request,
        template_name=template_to_use,
        context=base_context
    )


@login_required(login_url="/login/")
def password_change(request):
    template_name_to_use = 'account/password_change.html'
    if request.POST:
        error_message = check_fields(request.POST, {
            "password": "hasło"
        })

        if error_message:
            return render(
                request=request,
                template_name=template_name_to_use,
                context={"warning": error_message}
            )

        user = request.user
        user.set_password(request.POST.get("password"))
        user.save()
        request.session['info'] = "hasło zostało zaktualizowane"
        login(request, user)

        return redirect(
            profile_view.__name__
        )

    return render(
        request=request,
        template_name=template_name_to_use,
        context={}
    )


@login_required(login_url="/login/")
def change_user_data(request):
    template_name_to_use = 'account/change_user_data.html'
    if request.POST:
        u = request.user
        email = request.POST.get("email")
        first_name = request.POST.get("firstName")
        last_name = request.POST.get("lastName")

        if email:
            u.email = email
        if first_name:
            u.first_name = first_name
        if last_name:
            u.last_name = last_name

        u.save()
        login(request, u)
        return redirect(
            profile_view.__name__
        )

    return render(
        request=request,
        template_name=template_name_to_use,
        context={}
    )


@login_required(login_url='/login/')

programowanie_w_zastosowaniach/get_your_home/templates/announcement/add_edit_announcement.html
{% extends 'base.html' %}
{% block title %}
    <title>
        {% if ann %}
            Edytuj ogłoszenie
        {% else %}
            Dodaj ogłoszenie
        {% endif %}
    </title>
{% endblock %}

{% block content %}
    <div class="alert alert-warning" id="alert" role="alert"  {% if not warning %} hidden="hidden" {% endif %}>
        {{ warning }}
    </div>
    <form
            {% if ann %}
                action="edit"
            {% else %}
                action="/add/"
            {% endif %}
                method="POST"
                enctype="multipart/form-data"
    >
        <div class="grid">
            {% csrf_token %}
            <div class="form-group pt-2">
                <label for="typeOfAnn">Typ</label>
                <select class="form-control" id="typeOfAnn" name="typeOfAnn" required>
                    {% for ann_type, description in ann_types.items %}
                        <option value="{{ ann_type }}" {% if ann.type == ann_type %}selected{% endif %}>
                            {{ description }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group pt-2">
                <label for="typeOfStatus">Status</label>
                <select class="form-control" id="typeOfStatus" name="typeOfStatus" required>
                    {% for status_type, description in statutes.items %}
                        <option value="{{ status_type }}" {% if ann.status == status_type %}selected{% endif %}>{{ description }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group pt-2">
                <label for="typeOfHeating">Typ ogrzewania</label>
                <select class="form-control" id="typeOfHeating" name="typeOfHeating" required>
                    {% for heating_type, description in heating_types.items %}
                        <option value="{{ heating_type }}" {% if ann.heating_types == heating_type %}selected{% endif %}>{{ description }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group pt-2">
                <label for="price">Cena</label>
                <input type="number" class="form-control" min=0 id="price" name="price" required {% if ann %} value="{{ ann.price }}" {% endif %}>
            </div>
            <div class="form-group pt-2">
                <label for="buildYear">Rok budowy</label>
                <input type="number" class="form-control" min=1850 id="buildYear" name="buildYear" value=2023 required {% if ann %} value="{{ ann.build_year }}" {% endif %}>
            </div>
            <div class="form-group pt-2">
                <label for="area">Powierzchnia</label>
                <input type="number" class="form-control" min="0" id="area" name="area" required {% if ann %} value="{{ ann.area }}" {% endif %}>
            </div>
            <div class="form-group pt-2">
                <label for="city">Miasto</label>
                <input type="text" class="form-control" id="city" name="city" required {% if ann %} value="{{ ann.address_city }}" {% endif %}>
            </div>
            <div class="form-group pt-2">
                <label for="street">Ulica</label>
                <input type="text" class="form-control" id="street" name="street" required {% if ann %} value="{{ ann.address_street }}" {% endif %}>
            </div>
            <div class="form-group pt-2">
                <label for="addressNumber">Numer domu/mieszkania</label>
                <input type="text" class="form-control" id="addressNumber" name="addressNumber" required {% if ann %} value="{{ ann.address_number }}" {% endif %}>
            </div>
            <div class="form-group pt-2">
                <label for="postCode">Kod pocztowy</label>
                <input type="text" pattern="[0-9]{2}-[0-9]{3}" class="form-control" id="postCode" name="postCode" {% if ann %} value="{{ ann.address_post_code }}" {% endif %}>
            </div>
            <div class="form-group pt-2">
                <label for="roomsNumber">Ilość pokoi</label>
                <input type="text" class="form-control" id="roomsNumber" name="roomsNumber" {% if ann %} value="{{ ann.number_of_rooms }}" {% endif %}>
            </div>
            <div class="form-group pt-2">
                <label for="photo">Zdjęcie</label>
                <input type="file" id="photo" style="border: none;" placeholder="Dodanie zdjęcia" name="photo" {% if not ann %} required {% endif %}>
            </div>
        </div>
        <div class="grid-form">
            <div class="form-group pt-2">
                <label for="description">Opis</label>
                <textarea class="form-control" id="description" name="description" rows="3" required >{% if ann %} {{ ann.description }} {% endif %}</textarea>
            </div>
            <div class="form-group pt-2">
                <button type="submit" class="btn btn-primary">{% if ann %} Edytuj {% else %} Dodaj {% endif %} ogłoszenie</button>
            </div>
        </div>
    </form>
{% endblock %}

programowanie_w_zastosowaniach/get_your_home/templates/announcement/admin_edit.html
{% extends 'base.html' %}
{% block title %}
    <title>Aktualizacja ogłoszenia</title>
{% endblock %}

{% block content %}
    <main>
        {% if warning  %}
        <div class="alert alert-warning" role="alert">
          {{  warning }}
        </div>
    {% endif  %}
        <form action="admin" method="POST">
            {% csrf_token %}
            <div class="form-check">
                <input
                        class="form-check-input"
                        type="checkbox"
                        value="blocked"
                        id="block"
                        name="block"
                        {% if blocked %}
                        checked
                        disabled
                        {% endif %}
                >
                <label class="form-check-label" for="block">
                    Czy zablokować ogłoszenie?
                </label>
            </div>
            <div class="form-group">
                <label for="comment">Komentarz:</label>
                <textarea class="form-control" id="comment" name="comment" rows="3">{{ comment }}</textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-danger">Edytuj</button>
            </div>
        </form>
    </main>
{% endblock %}

programowanie_w_zastosowaniach/get_your_home/templates/announcement/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>{{ ann.get_type_display }} w {{ ann.address_city }}</title>
{% endblock %}


{% block content %}
    <style>
        .main-carousel .carousel-item {
            text-align: center;
        }

        .main-carousel img {
            max-height: 400px;
            margin: auto;
            display: inline-block;
        }

        .thumbnail-carousel .carousel-inner {
            white-space: nowrap;
            overflow-x: auto;
        }

        .thumbnail-carousel .carousel-item {
            display: inline-block;
            width: auto;
            cursor: pointer;
        }

        .thumbnail-carousel img {
            max-height: 100px;
            margin-right: 5px;
            opacity: 0.7;
        }

        .thumbnail-carousel img.active {
            opacity: 1;
        }

        .detail-description {
            font-size: 14px;
            color: #555;
            margin-top: 5px;
        }

        .description {
            display: block;
            background-color: #eee;
            border-radius: 3px;
            min-height: 300px;
            padding: 10px;
        }

        .blok-info {
            background-color: #eee;
            border-radius: 3px;
        }
    </style>
    {% if user.is_superuser %}
        <div class="row m-2">
            <a href="admin" class="btn btn-danger">Administracja ogłoszeniem</a>
        </div>
    {% endif %}
    {% if owner %}
        {% if not ann.status == "blocked" %}
        <div class="row m-2">
            <a href="edit" class="btn btn-outline-warning">Edytuj / zablokuj ogłoszenia</a>
        </div>
        {% endif %}
        {% if ann.admin_note %}
            {% if ann.status == "blocked" %}
                <div>
                    <div class="alert alert-danger" id="alert" role="alert">
                        {{ ann.admin_note }}
                    </div>
                </div>
            {% else %}
                <div>
                    <div class="alert alert-info" id="alert" role="alert">
                        {{ ann.admin_note }}
                    </div>
                </div>
            {% endif %}
        {% endif %}
    {% endif %}


    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            {% for photo in photos %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <img class="d-block w-100" src="{% get_media_prefix %}{{ photo.name }}" alt="{{ photo.alt_text }}">
                </div>
            {% endfor %}
        </div>
        <!-- Thumbnails Carousel -->
        <div id="thumbnailCarousel" class="carousel slide thumbnail-carousel" data-interval="false">
            <div class="carousel-inner">
                {% for photo in photos %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}" data-target="#mainCarousel"
                         data-slide-to="{{ forloop.counter0 }}">
                        <img src="{% get_media_prefix %}{{ photo.name }}" alt="Thumbnail" class="img-fluid">
                    </div>
                {% endfor %}
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>



    <div class="container mt-4">
        <h2 class="mb-4">Szczegóły ogłoszenia</h2>
        <div class="row">
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-3">
                <div class="d-flex p-3 border bg-light w-100">
                    <i class="fas fa-vector-square mr-3"></i>
                    <div>
                        <strong>Powierzchnia</strong><br>
                        {{ ann.area }} m²
                    </div>
                </div>
            </div>
            <!-- Repeat for each property, replacing icon and property as necessary -->
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-3">
                <div class="d-flex p-3 border bg-light w-100">
                    <i class="fas fa-door-closed mr-3"></i>
                    <div>
                        <strong>Liczba pokoi</strong><br>
                        {{ ann.number_of_rooms }}
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-3">
                <div class="d-flex p-3 border bg-light w-100">
                    <i class="fas fa-building mr-3"></i>
                    <div>
                        <strong>Piętro</strong><br>
                        {{ ann.floor|default:"Brak danych" }}
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-3">
                <div class="d-flex p-3 border bg-light w-100">
                    <i class="fas fa-building mr-3"></i>
                    <div>
                        <strong>Czynsz</strong><br>
                        {{ ann.price }} zł
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-3">
                <div class="d-flex p-3 border bg-light w-100">
                    <i class="fas fa-headset mr-3"></i>
                    <div>
                        <strong>Obsługa zdalna</strong><br>
                        Zapytaj
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-3">
                <div class="d-flex p-3 border bg-light w-100">
                    <i class="fas fa-hand-holding-usd mr-3"></i>
                    <div>
                        <strong>Forma własności</strong><br>
                        {{ ann.get_type_display }}
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-3">
                <div class="d-flex p-3 border bg-light w-100">
                    <i class="fas fa-paint-roller mr-3"></i>
                    <div>
                        <strong>Stan wykończenia</strong><br>
                        {{ ann.get_status_display }}
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-3">
                <div class="d-flex p-3 border bg-light w-100">
                    <i class="fas fa-tree mr-3"></i>
                    <div>
                        <strong>Balkon / ogród / taras</strong><br>
                        {{ ann.balcony_type|default:"Brak danych" }}
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 d-flex align-items-stretch mb-3">
                <div class="d-flex p-3 border bg-light w-100">
                    <i class="fas fa-thermometer-three-quarters mr-3"></i>
                    <div>
                        <strong>Ogrzewanie</strong><br>
                        {{ ann.get_heating_type_display|default:"Brak danych" }}
                    </div>
                </div>
            </div>
            <div class="form-group mt-5">
                <h2>Opis</h2>
                <p class="description">{{ ann.description }}</p>
            </div>
        </div>
    </div>
    </div>
{% endblock %}